### ISSUE TITLE
Add an own namespace

### ISSUE THREAD

**Issue by IceflowRE** [pinam45/dynamic_bitset#3]
Could you probably add an own namespace? Otherwise it may be a bit difficult to use in larger projects.

**Comment by pinam45** [comment]
Yes, it is a bit annoying but "dynamic_bitset" is quite a generic name and collision might append. I don't want to use my username as namespace so I will think about something short and that make sense to use as namespace and add it soon, it will be an opportunity to do a first release.

**Comment by pinam45** [comment]
Sorry for the delay, I had a lot of other stuff to do so It took me a long time but it is now done. The dynamic_bitset was moved to the "sul" namespace and is now the first library of the Simple Useful Libraries! Yep, I plan to do some other libraries when I have some time available. Also made a [first release](https://github.com/pinam45/dynamic_bitset/releases/tag/v1.0.0)!
