### ISSUE TITLE
push_back_block

### ISSUE THREAD

**Issue by soufianekhiat** [pinam45/dynamic_bitset#6]
To simplify serialization with json I use on my side a push_back_block:
```
constexpr void dynamic_bitset<Block, Allocator>::push_back_block(Block blockValue)
{
	m_blocks.push_back(blockValue);
}
```
Binary serialization used .data();
for json 'for each block' save an uint32 or uint64 based on internal blocktype

**Comment by pinam45** [comment]
Your function does not increase the size of the bitset, but you don't need a custom function to append a block to the bitset, there is already some ``.append()`` functions:
 - [constexpr void dynamic_bitset\<Block, Allocator\>::append(block_type block)](https://pinam45.github.io/dynamic_bitset/classsul_1_1dynamic__bitset.html#ade38b3856fe88abe85c8b4f9df8f3f2c)
 - [constexpr void dynamic_bitset\<Block, Allocator\>::append(std::initializer_list\<block_type\> blocks)](https://pinam45.github.io/dynamic_bitset/classsul_1_1dynamic__bitset.html#a7e22f3631230d83dee52c91697477e46)
 - [template\<typename BlockInputIterator\> constexpr void dynamic_bitset\<Block, Allocator\>::append(BlockInputIterator first, BlockInputIterator last)](https://pinam45.github.io/dynamic_bitset/classsul_1_1dynamic__bitset.html#ab8e8116bd49791ce18c2dc825cb5948e)

Furthermore, unless you want to optimize the size of your json, as json is a text format I would recommend serializing the bitset to text using the more readable 0/1 representation. It is also easier to do using the dynamic_bitset ``.to_string()`` function for serialization:
 - [[[nodiscard]] constexpr std::basic_string\<_CharT, _Traits, _Alloc\> to_string(_CharT zero = _CharT('0'), _CharT one = _CharT('1')) const](https://pinam45.github.io/dynamic_bitset/classsul_1_1dynamic__bitset.html#a5af8874097723447bec7d97fee25541d)

and one of the "from string" constructor for de-serialization:
 - form ``std::string_view``: [template\<typename _CharT, typename _Traits\> constexpr dynamic_bitset\<Block, Allocator\>::dynamic_bitset(std::basic_string_view\<_CharT, _Traits\> str, typename std::basic_string_view\<_CharT, _Traits\>::size_type pos = 0, typename std::basic_string_view\<_CharT, _Traits\>::size_type n = std::basic_string_view\<_CharT, _Traits\>::npos, _CharT zero = _CharT('0'), _CharT one = _CharT('1'), const allocator_type& allocator = allocator_type())](https://pinam45.github.io/dynamic_bitset/classsul_1_1dynamic__bitset.html#ade4a38b7afd0a1a61be651b7f1e6fa91)
 - from ``std::string``: [template\<typename _CharT, typename _Traits, typename _Alloc\> constexpr dynamic_bitset\<Block, Allocator\>::dynamic_bitset(const std::basic_string\<_CharT, _Traits, _Alloc\>& str, typename std::basic_string\<_CharT, _Traits, _Alloc\>::size_type pos = 0, typename std::basic_string\<_CharT, _Traits, _Alloc\>::size_type n = std::basic_string<_CharT, _Traits, _Alloc>::npos, _CharT zero = _CharT('0'), _CharT one = _CharT('1'), const allocator_type& allocator = allocator_type())](https://pinam45.github.io/dynamic_bitset/classsul_1_1dynamic__bitset.html#a72979987d5f4c4cfbf4c9528905f414c)
 - from ``char*``: [template\<typename _CharT, typename _Traits\> constexpr dynamic_bitset\<Block, Allocator\>::dynamic_bitset(const _CharT* str, typename std::basic_string\<_CharT\>::size_type pos = 0, typename std::basic_string\<_CharT\>::size_type n = std::basic_string<_CharT>::npos, _CharT zero = _CharT('0'), _CharT one = _CharT('1'), const allocator_type& allocator = allocator_type())](https://pinam45.github.io/dynamic_bitset/classsul_1_1dynamic__bitset.html#a48f7cc8cc4daf3485b4f305e3e473dc6)

beautifully unreadable, click on the links to see something more understandable in the online documentation.

For example, using [ nlohmann/json](https://github.com/nlohmann/json):
```cpp
#include "sul/dynamic_bitset.hpp"
#include "nlohmann/json.hpp"
#include <iostream>
#include <cassert>

int main()
{
    sul::dynamic_bitset<> bitset1(12, 0b0100010110111);
    std::cout << "bitset1     = " << bitset1 << std::endl;
    sul::dynamic_bitset<> bitset2("100111011");
    std::cout << "bitset2     = " << bitset2 << std::endl;

    nlohmann::json json;
    json["bitset1"] = bitset1.to_string();
    json["bitset2"] = bitset2.to_string();
    std::cout << "json = " << json.dump(4) << std::endl;

    sul::dynamic_bitset<> bitset1_from_json(json["bitset1"].get<std::string>());
    assert(bitset1_from_json == bitset1);
    sul::dynamic_bitset<> bitset2_from_json(json["bitset2"].get<std::string>());
    assert(bitset2_from_json == bitset2);
    return 0;
}
```
all asserts succeed, the program return 0 and outputs:
```
bitset1     = 100010110111
bitset2     = 100111011
json = {
    "bitset1": "100010110111",
    "bitset2": "100111011"
}
```
you can try it online on [godbolt.org](https://godbolt.org/z/vMePsY)

**Comment by pinam45** [comment]
Using [ nlohmann/json](https://github.com/nlohmann/json) you can even get rid of the ``.to_string()`` and ``.get<std::string>()`` by defining the ``to_json()`` and ``from_json()`` functions in the ``sul`` namespace:
```cpp
#include "sul/dynamic_bitset.hpp"
#include "nlohmann/json.hpp"
#include <iostream>
#include <cassert>

namespace sul
{
    template<typename Block, typename Allocator>
    void to_json(nlohmann::json& j, const sul::dynamic_bitset<Block, Allocator>& b)
    {
        j = b.to_string();
    }

    template<typename Block, typename Allocator>
    void from_json(const nlohmann::json& j, sul::dynamic_bitset<Block, Allocator>& b)
    {
        b = sul::dynamic_bitset<>(j.get<std::string>());
    }
}

int main()
{
    sul::dynamic_bitset<> bitset1(12, 0b0100010110111);
    std::cout << "bitset1     = " << bitset1 << std::endl;
    sul::dynamic_bitset<> bitset2("100111011");
    std::cout << "bitset2     = " << bitset2 << std::endl;

    nlohmann::json json;
    json["bitset1"] = bitset1;
    json["bitset2"] = bitset2;
    std::cout << "json = " << json.dump(4) << std::endl;

    sul::dynamic_bitset<> bitset1_from_json;
    json["bitset1"].get_to(bitset1_from_json);
    assert(bitset1_from_json == bitset1);
    sul::dynamic_bitset<> bitset2_from_json;
    json["bitset2"].get_to(bitset2_from_json);
    assert(bitset2_from_json == bitset2);
    return 0;
}

```
all asserts succeed, the program return 0 and outputs:
```
bitset1     = 100010110111
bitset2     = 100111011
json = {
    "bitset1": "100010110111",
    "bitset2": "100111011"
}
```
you can try it online on [godbolt.org](https://godbolt.org/z/W1TsWE)

**Comment by soufianekhiat** [comment]
Thanks,
In term of a footprint, a collection of int (on average) seem more consistent.
"bitset1": [7]
vs
"bitset1": "111"
