### ISSUE TITLE
Compatibility with fmt

### ISSUE THREAD

**Issue by soufianekhiat** [pinam45/dynamic_bitset#8]
I wonder if we can make sul::dynamic_bitset compatible with fmt (https://fmt.dev/latest/index.html, https://hackingcpp.com/cpp/libs/fmt.html).
To do so, I think the missing is the begin/end accessing directly one bit with an iterator class (not for blocks) and an constructor with std::initializer_list< bool >.
https://hackingcpp.com/cpp/libs/fmt.html#panel-fold68a

Any thought on that?

**Comment by pinam45** [comment]
Hello, thanks for the idea of being compatible with fmt, I love this lib, as for the begin/end iterator the [boost::dynamic_bitset documentation](https://www.boost.org/doc/libs/1_49_0/libs/dynamic_bitset/dynamic_bitset.html) explain quite well the choice to not add them:

> dynamic_bitset is not a [Container](http://www.sgi.com/tech/stl/Container.html) and does not provide iterators for the following reason:
> 
> A container with a proxy reference type can not fulfill the container requirements as specified in the C++ standard (unless one resorts to strange iterator semantics). std::vector<bool> has a proxy reference type and does not fulfill the container requirements and as a result has caused many problems. One common problem is when people try to use iterators from std::vector<bool> with a Standard algorithm such as std::search. The std::search requirements say that the iterator must be a [Forward Iterator](http://www.sgi.com/tech/stl/ForwardIterator.html), but the std::vector<bool>::iterator does not meet this requirement because of the proxy reference. Depending on the implementation, they may or not be a compile error or even a run-time error due to this misuse. For further discussion of the problem see Effective STL by Scott Meyers). So dynamic_bitset tries to avoid these problems by not pretending to be a container.

(The links Boost used send to an HPE website asking for authentication but you can get all the Container requirements at https://eel.is/c++draft/container.requirements and all the Forward Iterator requirements at https://eel.is/c++draft/forward.iterators.)

But fmt has [std::ostream support](https://fmt.dev/latest/api.html#std-ostream-support) with `fmt/ostream.h` for types that have an overloaded insertion operator (`operator<<`), and the `sul::dynamic_bitset<>` type have [one](https://pinam45.github.io/dynamic_bitset/namespacesul.html#aa60cc8803d96c61359eb54e2cea18c5a), so you can do:

```cpp
#include <sul/dynamic_bitset.hpp>
#include <fmt/ostream.h>

int main()
{
    sul::dynamic_bitset<> bitset(12, 0b0100010110111);
    fmt::print("bitset: {}\n", bitset);

    return 0;
}
```
output:

    bitset: 100010110111

Test it on [godbolt.org](https://godbolt.org/z/hY9ve5nE1).

**Comment by soufianekhiat** [comment]
I understand boost argument, I was thinking more about cbegin & cend implementation only for constant iterator, read_only. The solution with fmt/ostream should work.

**Comment by pinam45** [comment]
Sorry for the response time, I missed the notification.
The boost argument also concern const iterators, the example with std::search requiring a [Forward Iterator](http://www.sgi.com/tech/stl/ForwardIterator.html) is also work with const iterators.
